-- Create ServiceRequest Module Tables
-- Oracle Database with 30-character limit for identifiers

-- 1. Create BMM_SERVICE_REQUESTS table
CREATE TABLE BMM_SERVICE_REQUESTS (
    ID VARCHAR2(36) NOT NULL,
    CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    UPDATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    DELETED_AT TIMESTAMP,
    CREATED_BY VARCHAR2(50),
    UPDATED_BY VARCHAR2(50),
    VERSION NUMBER NOT NULL,
    
    -- HIS Integration Fields
    HIS_SERVICE_REQ_ID NUMBER,
    SERVICE_REQ_CODE VARCHAR2(50) NOT NULL,
    
    -- Status & Type
    SERVICE_REQ_STT_ID NUMBER NOT NULL,
    SERVICE_REQ_STT_CODE VARCHAR2(10) NOT NULL,
    SERVICE_REQ_TYPE_ID NUMBER NOT NULL,
    SERVICE_REQ_TYPE_CODE VARCHAR2(10) NOT NULL,
    
    -- Timing
    INSTRUCTION_TIME TIMESTAMP NOT NULL,
    INSTRUCTION_DATE DATE NOT NULL,
    
    -- Medical Information
    ICD_CODE VARCHAR2(20),
    ICD_NAME VARCHAR2(500),
    ICD_SUB_CODE VARCHAR2(100),
    ICD_TEXT CLOB,
    
    -- Treatment Reference
    TREATMENT_ID NUMBER,
    TREATMENT_CODE VARCHAR2(50),
    
    -- Patient Information (Denormalized)
    PATIENT_ID NUMBER NOT NULL,
    PATIENT_CODE VARCHAR2(50) NOT NULL,
    PATIENT_NAME VARCHAR2(200) NOT NULL,
    PATIENT_DOB NUMBER NOT NULL,
    PATIENT_CMND_NUMBER VARCHAR2(20),
    PATIENT_CMND_DATE NUMBER,
    PATIENT_CMND_PLACE VARCHAR2(100),
    PATIENT_MOBILE VARCHAR2(20),
    PATIENT_PHONE VARCHAR2(20),
    PATIENT_PROVINCE_CODE VARCHAR2(10),
    PATIENT_PROVINCE_NAME VARCHAR2(100),
    PATIENT_COMMUNE_CODE VARCHAR2(10),
    PATIENT_COMMUNE_NAME VARCHAR2(100),
    PATIENT_ADDRESS CLOB NOT NULL,
    PATIENT_GENDER_ID NUMBER NOT NULL,
    PATIENT_GENDER_NAME VARCHAR2(50) NOT NULL,
    PATIENT_CAREER_NAME VARCHAR2(100),
    
    -- LIS Patient Reference
    LIS_PATIENT_ID VARCHAR2(36),
    
    -- Room & Department Information
    REQUEST_ROOM_ID NUMBER,
    REQUEST_ROOM_CODE VARCHAR2(50),
    REQUEST_ROOM_NAME VARCHAR2(200),
    REQUEST_DEPARTMENT_ID NUMBER,
    REQUEST_DEPARTMENT_CODE VARCHAR2(50),
    REQUEST_DEPARTMENT_NAME VARCHAR2(200),
    EXECUTE_ROOM_ID NUMBER,
    EXECUTE_ROOM_CODE VARCHAR2(50),
    EXECUTE_ROOM_NAME VARCHAR2(200),
    EXECUTE_DEPARTMENT_ID NUMBER,
    EXECUTE_DEPARTMENT_CODE VARCHAR2(50),
    EXECUTE_DEPARTMENT_NAME VARCHAR2(200),
    
    -- Additional Fields
    NOTE CLOB,
    TOTAL_AMOUNT NUMBER(15,2) DEFAULT 0,
    STATUS VARCHAR2(20) DEFAULT 'PENDING',
    IS_ACTIVE NUMBER DEFAULT 1,
    
    CONSTRAINT PK_BMM_SERVICE_REQUESTS PRIMARY KEY (ID),
    CONSTRAINT UK_BMM_SR_CODE UNIQUE (SERVICE_REQ_CODE)
);

-- 2. Create BMM_SERVICE_REQ_ITEMS table
CREATE TABLE BMM_SERVICE_REQ_ITEMS (
    ID VARCHAR2(36) NOT NULL,
    CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    UPDATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    DELETED_AT TIMESTAMP,
    CREATED_BY VARCHAR2(50),
    UPDATED_BY VARCHAR2(50),
    VERSION NUMBER NOT NULL,
    
    -- Service Request Reference
    SR_ID VARCHAR2(36) NOT NULL,
    
    -- HIS Integration Fields
    HIS_SERE_SERV_ID NUMBER NOT NULL,
    HIS_SERVICE_ID NUMBER NOT NULL,
    HIS_SERVICE_CODE VARCHAR2(50) NOT NULL,
    HIS_SERVICE_NAME VARCHAR2(200) NOT NULL,
    HIS_PRICE NUMBER(10,2) NOT NULL,
    
    -- LIS Service Reference
    LIS_SERVICE_ID VARCHAR2(36),
    LIS_SERVICE_CODE VARCHAR2(50),
    LIS_SERVICE_NAME VARCHAR2(200),
    LIS_SHORT_NAME VARCHAR2(100),
    LIS_CURRENT_PRICE NUMBER(10,2),
    
    -- Service Group & Unit of Measure
    SERVICE_GROUP_ID VARCHAR2(36),
    SERVICE_GROUP_NAME VARCHAR2(200),
    UNIT_OF_MEASURE_ID VARCHAR2(36),
    UNIT_OF_MEASURE_NAME VARCHAR2(100),
    
    -- Quantity & Pricing
    QUANTITY NUMBER(10,2) DEFAULT 1,
    UNIT_PRICE NUMBER(10,2) NOT NULL,
    TOTAL_PRICE NUMBER(15,2) NOT NULL,
    
    -- Status & Order
    STATUS VARCHAR2(20) DEFAULT 'PENDING',
    ITEM_ORDER NUMBER DEFAULT 1,
    IS_ACTIVE NUMBER DEFAULT 1,
    
    CONSTRAINT PK_BMM_SERVICE_REQ_ITEMS PRIMARY KEY (ID)
);

-- 3. Create BMM_SR_ITEM_TESTS table
CREATE TABLE BMM_SR_ITEM_TESTS (
    ID VARCHAR2(36) NOT NULL,
    CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    UPDATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    DELETED_AT TIMESTAMP,
    CREATED_BY VARCHAR2(50),
    UPDATED_BY VARCHAR2(50),
    VERSION NUMBER NOT NULL,
    
    SR_ITEM_ID VARCHAR2(36) NOT NULL,
    SERVICE_TEST_ID VARCHAR2(36) NOT NULL,
    TEST_CODE VARCHAR2(50) NOT NULL,
    TEST_NAME VARCHAR2(200) NOT NULL,
    SHORT_NAME VARCHAR2(100),
    TEST_ORDER NUMBER DEFAULT 1,
    IS_ACTIVE NUMBER DEFAULT 1,
    
    CONSTRAINT PK_BMM_SR_ITEM_TESTS PRIMARY KEY (ID)
);

-- Create Indexes for BMM_SERVICE_REQUESTS
CREATE INDEX IDX_BMM_SR_CODE ON BMM_SERVICE_REQUESTS(SERVICE_REQ_CODE);
CREATE INDEX IDX_BMM_SR_PATIENT ON BMM_SERVICE_REQUESTS(PATIENT_ID);
CREATE INDEX IDX_BMM_SR_TREATMENT ON BMM_SERVICE_REQUESTS(TREATMENT_ID);
CREATE INDEX IDX_BMM_SR_ACTIVE ON BMM_SERVICE_REQUESTS(IS_ACTIVE);
CREATE INDEX IDX_BMM_SR_HIS_ID ON BMM_SERVICE_REQUESTS(HIS_SERVICE_REQ_ID);
CREATE INDEX IDX_BMM_SR_LIS_PATIENT ON BMM_SERVICE_REQUESTS(LIS_PATIENT_ID);

-- Create Indexes for BMM_SERVICE_REQ_ITEMS
CREATE INDEX IDX_BMM_SR_ITEMS_SR_ID ON BMM_SERVICE_REQ_ITEMS(SR_ID);
CREATE INDEX IDX_BMM_SR_ITEMS_HIS_ID ON BMM_SERVICE_REQ_ITEMS(HIS_SERE_SERV_ID);
CREATE INDEX IDX_BMM_SR_ITEMS_LIS_ID ON BMM_SERVICE_REQ_ITEMS(LIS_SERVICE_ID);
CREATE INDEX IDX_BMM_SR_ITEMS_ACTIVE ON BMM_SERVICE_REQ_ITEMS(IS_ACTIVE);

-- Create Indexes for BMM_SR_ITEM_TESTS
CREATE INDEX IDX_BMM_SR_ITEM_TESTS_SR_ID ON BMM_SR_ITEM_TESTS(SR_ITEM_ID);
CREATE INDEX IDX_BMM_SR_ITEM_TESTS_TEST_ID ON BMM_SR_ITEM_TESTS(SERVICE_TEST_ID);
CREATE INDEX IDX_BMM_SR_ITEM_TESTS_ACTIVE ON BMM_SR_ITEM_TESTS(IS_ACTIVE);

-- Create Foreign Key Constraints
ALTER TABLE BMM_SERVICE_REQ_ITEMS 
ADD CONSTRAINT FK_BMM_SR_ITEMS_SR_ID 
FOREIGN KEY (SR_ID) REFERENCES BMM_SERVICE_REQUESTS(ID);

ALTER TABLE BMM_SR_ITEM_TESTS 
ADD CONSTRAINT FK_BMM_SR_ITEM_TESTS_SR_ITEM_ID 
FOREIGN KEY (SR_ITEM_ID) REFERENCES BMM_SERVICE_REQ_ITEMS(ID);

-- Add Comments
COMMENT ON TABLE BMM_SERVICE_REQUESTS IS 'Service Requests from HIS system';
COMMENT ON TABLE BMM_SERVICE_REQ_ITEMS IS 'Service Request Items - individual services';
COMMENT ON TABLE BMM_SR_ITEM_TESTS IS 'Service Request Item Tests - individual tests';

COMMENT ON COLUMN BMM_SERVICE_REQUESTS.SERVICE_REQ_CODE IS 'Service Request Code from HIS';
COMMENT ON COLUMN BMM_SERVICE_REQUESTS.LIS_PATIENT_ID IS 'LIS Patient ID reference';
COMMENT ON COLUMN BMM_SERVICE_REQ_ITEMS.SR_ID IS 'Service Request ID reference';
COMMENT ON COLUMN BMM_SERVICE_REQ_ITEMS.LIS_SERVICE_ID IS 'LIS Service ID reference';
COMMENT ON COLUMN BMM_SR_ITEM_TESTS.SR_ITEM_ID IS 'Service Request Item ID reference';
