# Kong Gateway Configuration for Bach Mai LIS Management System

# Services Configuration
services:
  - name: bach-mai-lis-api
    url: http://localhost:3000
    tags:
      - bach-mai-lis
      - api
    connect_timeout: 60000
    write_timeout: 60000
    read_timeout: 60000

# Routes Configuration
routes:
  # Public Routes (No Authentication Required)
  - name: bach-mai-lis-public-routes
    service: bach-mai-lis-api
    paths:
      - /KONGAPI/api/v1/auth/login
      - /KONGAPI/api/v1/auth/register
      - /KONGAPI/api/v1/health
      - /KONGAPI/api/v1/ready
    methods:
      - GET
      - POST
    strip_path: false
    preserve_host: true
    tags:
      - bach-mai-lis
      - public

  # Protected Routes (JWT Authentication Required)
  - name: bach-mai-lis-protected-routes
    service: bach-mai-lis-api
    paths:
      - /KONGAPI/api/v1/users
      - /KONGAPI/api/v1/auth/logout
      - /KONGAPI/api/v1/auth/refresh
    methods:
      - GET
      - POST
      - PUT
      - PATCH
      - DELETE
    strip_path: false
    preserve_host: true
    tags:
      - bach-mai-lis
      - protected

  # Admin Routes (Admin Role Required)
  - name: bach-mai-lis-admin-routes
    service: bach-mai-lis-api
    paths:
      - /KONGAPI/api/v1/admin
    methods:
      - GET
      - POST
      - PUT
      - PATCH
      - DELETE
    strip_path: false
    preserve_host: true
    tags:
      - bach-mai-lis
      - admin

# Plugins Configuration
plugins:
  # CORS Plugin (Global)
  - name: cors
    config:
      origins:
        - "*"
      methods:
        - GET
        - POST
        - PUT
        - PATCH
        - DELETE
        - OPTIONS
      headers:
        - Accept
        - Accept-Version
        - Content-Length
        - Content-MD5
        - Content-Type
        - Date
        - X-Auth-Token
        - Authorization
        - X-Consumer-ID
        - X-Consumer-Username
        - X-Consumer-Custom-ID
        - X-Kong-Request-ID
      exposed_headers:
        - X-Auth-Token
        - X-Consumer-ID
        - X-Consumer-Username
        - X-Consumer-Custom-ID
        - X-Kong-Request-ID
      credentials: true
      max_age: 3600
      preflight_continue: false

  # Rate Limiting Plugin (Global)
  - name: rate-limiting
    config:
      minute: 100
      hour: 1000
      policy: local
      fault_tolerant: true
      hide_client_headers: false

  # Request/Response Transformer Plugin (Global)
  - name: request-transformer
    config:
      add:
        headers:
          - "X-Kong-Request-ID:$(uuid)"
      remove:
        headers:
          - "X-Forwarded-For"

  # JWT Plugin (Protected Routes Only)
  - name: jwt
    route: bach-mai-lis-protected-routes
    config:
      uri_param_names:
        - jwt
      cookie_names:
        - jwt
      header_names:
        - Authorization
      claims_to_verify:
        - exp
        - iat
      anonymous: null
      run_on_preflight: false
      maximum_expiration: 0
      algorithm: HS256
      key_claim_name: iss
      secret_is_base64: false

  # JWT Plugin (Admin Routes Only)
  - name: jwt
    route: bach-mai-lis-admin-routes
    config:
      uri_param_names:
        - jwt
      cookie_names:
        - jwt
      header_names:
        - Authorization
      claims_to_verify:
        - exp
        - iat
      anonymous: null
      run_on_preflight: false
      maximum_expiration: 0
      algorithm: HS256
      key_claim_name: iss
      secret_is_base64: false

  # Prometheus Plugin (Protected Routes)
  - name: prometheus
    route: bach-mai-lis-protected-routes
    config:
      per_consumer: true
      status_code_metrics: true
      latency_metrics: true
      bandwidth_metrics: true
      upstream_health_metrics: true

# Consumers Configuration
consumers:
  - username: admin-user
    custom_id: admin-001
    tags:
      - admin
      - bach-mai-lis
    jwt_secrets:
      - key: admin-secret-key
        secret: your-admin-jwt-secret-key-here
        algorithm: HS256

  - username: regular-user
    custom_id: user-001
    tags:
      - user
      - bach-mai-lis
    jwt_secrets:
      - key: user-secret-key
        secret: your-user-jwt-secret-key-here
        algorithm: HS256

# ACL Plugin Configuration
acls:
  - consumer: admin-user
    group: admin
    tags:
      - admin
      - bach-mai-lis

  - consumer: regular-user
    group: user
    tags:
      - user
      - bach-mai-lis

# ACL Plugin (Admin Routes)
plugins:
  - name: acl
    route: bach-mai-lis-admin-routes
    config:
      hide_groups_header: false
      allow:
        - admin
      deny:
        - user
