-- Migration: Update User entity to use fullName instead of firstName/lastName
-- Date: 2025-10-10
-- Description: Replace FIRST_NAME and LAST_NAME columns with FULL_NAME column

-- Add new FULL_NAME column
ALTER TABLE BMM_USERS ADD FULL_NAME VARCHAR2(100);

-- Update existing data (concatenate firstName + lastName)
UPDATE BMM_USERS 
SET FULL_NAME = TRIM(FIRST_NAME || ' ' || LAST_NAME)
WHERE FIRST_NAME IS NOT NULL AND LAST_NAME IS NOT NULL;

-- Make FULL_NAME NOT NULL after data migration
ALTER TABLE BMM_USERS MODIFY FULL_NAME NOT NULL;

-- Drop old columns
ALTER TABLE BMM_USERS DROP COLUMN FIRST_NAME;
ALTER TABLE BMM_USERS DROP COLUMN LAST_NAME;

-- Add index for fullName search
CREATE INDEX IDX_BMM_USERS_FULL_NAME ON BMM_USERS(FULL_NAME);

-- Add new fields for location and department
ALTER TABLE BMM_USERS ADD PROVINCE_ID VARCHAR2(36);
ALTER TABLE BMM_USERS ADD WARD_ID VARCHAR2(36);
ALTER TABLE BMM_USERS ADD DEPARTMENT_ID VARCHAR2(36);

-- Add indexes for new fields
CREATE INDEX IDX_BMM_USERS_PROVINCE_ID ON BMM_USERS(PROVINCE_ID);
CREATE INDEX IDX_BMM_USERS_WARD_ID ON BMM_USERS(WARD_ID);
CREATE INDEX IDX_BMM_USERS_DEPARTMENT_ID ON BMM_USERS(DEPARTMENT_ID);

-- Add foreign key constraints
ALTER TABLE BMM_USERS ADD CONSTRAINT FK_USER_PROVINCE 
    FOREIGN KEY (PROVINCE_ID) REFERENCES BMM_PROVINCES(ID);

ALTER TABLE BMM_USERS ADD CONSTRAINT FK_USER_WARD 
    FOREIGN KEY (WARD_ID) REFERENCES BMM_WARDS(ID);

ALTER TABLE BMM_USERS ADD CONSTRAINT FK_USER_DEPARTMENT 
    FOREIGN KEY (DEPARTMENT_ID) REFERENCES BMM_DEPARTMENTS(ID);

COMMIT;
