-- Migration: Create fresh BMM_USERS table with correct schema
-- Date: 2025-10-10
-- Description: Create User table from scratch with fullName and relationships

-- Drop table if exists (for fresh start)
DECLARE
    table_exists NUMBER;
BEGIN
    SELECT COUNT(*) INTO table_exists
    FROM USER_TABLES 
    WHERE TABLE_NAME = 'BMM_USERS';
    
    IF table_exists > 0 THEN
        EXECUTE IMMEDIATE 'DROP TABLE BMM_USERS CASCADE CONSTRAINTS';
    END IF;
END;
/

-- Create BMM_USERS table with correct schema
CREATE TABLE BMM_USERS (
    ID VARCHAR2(36) PRIMARY KEY,
    USERNAME VARCHAR2(50) NOT NULL UNIQUE,
    EMAIL VARCHAR2(100) NOT NULL UNIQUE,
    PASSWORD_HASH VARCHAR2(255) NOT NULL,
    FULL_NAME VARCHAR2(100) NOT NULL,
    PHONE_NUMBER VARCHAR2(20),
    DATE_OF_BIRTH DATE,
    ADDRESS VARCHAR2(500),
    ROLE VARCHAR2(20) DEFAULT 'user' NOT NULL,
    IS_ACTIVE NUMBER(1) DEFAULT 1 NOT NULL,
    LAST_LOGIN_AT TIMESTAMP,
    HIS_USERNAME VARCHAR2(100),
    HIS_PASSWORD VARCHAR2(255),
    PROVINCE_ID VARCHAR2(36),
    WARD_ID VARCHAR2(36),
    DEPARTMENT_ID VARCHAR2(36),
    CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    UPDATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    DELETED_AT TIMESTAMP,
    CREATED_BY VARCHAR2(50),
    UPDATED_BY VARCHAR2(50),
    VERSION NUMBER DEFAULT 1 NOT NULL
);

-- Create indexes
CREATE INDEX IDX_BMM_USERS_USERNAME ON BMM_USERS(USERNAME);
CREATE INDEX IDX_BMM_USERS_EMAIL ON BMM_USERS(EMAIL);
CREATE INDEX IDX_BMM_USERS_FULL_NAME ON BMM_USERS(FULL_NAME);
CREATE INDEX IDX_BMM_USERS_ROLE ON BMM_USERS(ROLE);
CREATE INDEX IDX_BMM_USERS_IS_ACTIVE ON BMM_USERS(IS_ACTIVE);
CREATE INDEX IDX_BMM_USERS_PROVINCE_ID ON BMM_USERS(PROVINCE_ID);
CREATE INDEX IDX_BMM_USERS_WARD_ID ON BMM_USERS(WARD_ID);
CREATE INDEX IDX_BMM_USERS_DEPARTMENT_ID ON BMM_USERS(DEPARTMENT_ID);
CREATE INDEX IDX_BMM_USERS_CREATED_AT ON BMM_USERS(CREATED_AT);

-- Add foreign key constraints (if referenced tables exist)
DECLARE
    table_exists NUMBER;
BEGIN
    -- Check if BMM_PROVINCES exists
    SELECT COUNT(*) INTO table_exists
    FROM USER_TABLES 
    WHERE TABLE_NAME = 'BMM_PROVINCES';
    
    IF table_exists > 0 THEN
        EXECUTE IMMEDIATE 'ALTER TABLE BMM_USERS ADD CONSTRAINT FK_USER_PROVINCE 
            FOREIGN KEY (PROVINCE_ID) REFERENCES BMM_PROVINCES(ID)';
    END IF;
    
    -- Check if BMM_WARDS exists
    SELECT COUNT(*) INTO table_exists
    FROM USER_TABLES 
    WHERE TABLE_NAME = 'BMM_WARDS';
    
    IF table_exists > 0 THEN
        EXECUTE IMMEDIATE 'ALTER TABLE BMM_USERS ADD CONSTRAINT FK_USER_WARD 
            FOREIGN KEY (WARD_ID) REFERENCES BMM_WARDS(ID)';
    END IF;
    
    -- Check if BMM_DEPARTMENTS exists
    SELECT COUNT(*) INTO table_exists
    FROM USER_TABLES 
    WHERE TABLE_NAME = 'BMM_DEPARTMENTS';
    
    IF table_exists > 0 THEN
        EXECUTE IMMEDIATE 'ALTER TABLE BMM_USERS ADD CONSTRAINT FK_USER_DEPARTMENT 
            FOREIGN KEY (DEPARTMENT_ID) REFERENCES BMM_DEPARTMENTS(ID)';
    END IF;
END;
/

COMMIT;
