-- Migration: Create BMM_SERVICE_GROUPS table
-- Date: 2025-10-13
-- Description: Create Service Group table with serviceGroupCode, serviceGroupName, shortName, mapping

-- Drop table if exists (for fresh start)
DECLARE
    table_exists NUMBER;
BEGIN
    SELECT COUNT(*) INTO table_exists
    FROM USER_TABLES 
    WHERE TABLE_NAME = 'BMM_SERVICE_GROUPS';
    
    IF table_exists > 0 THEN
        EXECUTE IMMEDIATE 'DROP TABLE BMM_SERVICE_GROUPS CASCADE CONSTRAINTS';
    END IF;
END;
/

-- Create BMM_SERVICE_GROUPS table
CREATE TABLE BMM_SERVICE_GROUPS (
    ID VARCHAR2(36) PRIMARY KEY,
    SERVICE_GROUP_CODE VARCHAR2(50) NOT NULL UNIQUE,
    SERVICE_GROUP_NAME VARCHAR2(200) NOT NULL,
    SHORT_NAME VARCHAR2(50) NOT NULL,
    MAPPING VARCHAR2(500),
    CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    UPDATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    DELETED_AT TIMESTAMP,
    CREATED_BY VARCHAR2(50),
    UPDATED_BY VARCHAR2(50),
    VERSION NUMBER DEFAULT 1 NOT NULL
);

-- Create indexes
CREATE INDEX IDX_BMM_SERVICE_GROUPS_CODE ON BMM_SERVICE_GROUPS(SERVICE_GROUP_CODE);
CREATE INDEX IDX_BMM_SERVICE_GROUPS_NAME ON BMM_SERVICE_GROUPS(SERVICE_GROUP_NAME);
CREATE INDEX IDX_BMM_SERVICE_GROUPS_SHORT_NAME ON BMM_SERVICE_GROUPS(SHORT_NAME);
CREATE INDEX IDX_BMM_SERVICE_GROUPS_CREATED_AT ON BMM_SERVICE_GROUPS(CREATED_AT);

-- Insert sample data
INSERT INTO BMM_SERVICE_GROUPS (ID, SERVICE_GROUP_CODE, SERVICE_GROUP_NAME, SHORT_NAME, MAPPING) VALUES 
('550e8400-e29b-41d4-a716-446655440001', 'LAB_001', 'Laboratory Services', 'LAB', '{"hisCode": "LAB001", "externalSystem": "LIS"}');

INSERT INTO BMM_SERVICE_GROUPS (ID, SERVICE_GROUP_CODE, SERVICE_GROUP_NAME, SHORT_NAME, MAPPING) VALUES 
('550e8400-e29b-41d4-a716-446655440002', 'RAD_001', 'Radiology Services', 'RAD', '{"hisCode": "RAD001", "externalSystem": "RIS"}');

INSERT INTO BMM_SERVICE_GROUPS (ID, SERVICE_GROUP_CODE, SERVICE_GROUP_NAME, SHORT_NAME, MAPPING) VALUES 
('550e8400-e29b-41d4-a716-446655440003', 'PHARM_001', 'Pharmacy Services', 'PHARM', '{"hisCode": "PHARM001", "externalSystem": "PIS"}');

COMMIT;
