-- Migration: Add missing fields to BMM_SERVICE_TESTS table
-- Date: 2025-10-23
-- Description: Add test status, results, and processing fields to ServiceTest entity

-- Add new columns to BMM_SERVICE_TESTS
ALTER TABLE BMM_SERVICE_TESTS ADD (
    TEST_STATUS VARCHAR2(20) DEFAULT 'PENDING',
    EXPECTED_RESULT VARCHAR2(200),
    ACTUAL_RESULT VARCHAR2(200),
    RESULT_UNIT VARCHAR2(50),
    NORMAL_RANGE VARCHAR2(100),
    CRITICAL_VALUES CLOB,
    TEST_METHOD VARCHAR2(100),
    SPECIMEN_TYPE VARCHAR2(100),
    PROCESSING_TIME VARCHAR2(50)
);

-- Add comments for new columns
COMMENT ON COLUMN BMM_SERVICE_TESTS.TEST_STATUS IS 'Test status: PENDING, IN_PROGRESS, COMPLETED, CANCELLED';
COMMENT ON COLUMN BMM_SERVICE_TESTS.EXPECTED_RESULT IS 'Expected test result value';
COMMENT ON COLUMN BMM_SERVICE_TESTS.ACTUAL_RESULT IS 'Actual test result value';
COMMENT ON COLUMN BMM_SERVICE_TESTS.RESULT_UNIT IS 'Unit of measurement for results';
COMMENT ON COLUMN BMM_SERVICE_TESTS.NORMAL_RANGE IS 'Normal range for results';
COMMENT ON COLUMN BMM_SERVICE_TESTS.CRITICAL_VALUES IS 'Critical values in JSON format';
COMMENT ON COLUMN BMM_SERVICE_TESTS.TEST_METHOD IS 'Test method used';
COMMENT ON COLUMN BMM_SERVICE_TESTS.SPECIMEN_TYPE IS 'Type of specimen required';
COMMENT ON COLUMN BMM_SERVICE_TESTS.PROCESSING_TIME IS 'Expected processing time';

-- Create indexes for new columns
CREATE INDEX IDX_BMM_ST_TEST_STATUS ON BMM_SERVICE_TESTS(TEST_STATUS);
CREATE INDEX IDX_BMM_ST_SPECIMEN_TYPE ON BMM_SERVICE_TESTS(SPECIMEN_TYPE);
CREATE INDEX IDX_BMM_ST_TEST_METHOD ON BMM_SERVICE_TESTS(TEST_METHOD);

-- Update existing records to have default values
UPDATE BMM_SERVICE_TESTS SET TEST_STATUS = 'PENDING' WHERE TEST_STATUS IS NULL;
